### ISSUE TITLE
GFX error while running

### ISSUE THREAD

**Issue by HedgeHao** [NVIDIA-AI-IOT/YOLOv5-with-Isaac-ROS#8]
Following the steps in readme. Compile success. when running 
```
ros2 launch yolov5_isaac_ros isaac_ros_yolov5_tensor_rt.launch.py model_file_path:=/workspaces/isaac_ros-dev/src/yolov5s.onnx engine_file_path:=/workspaces/isaac_ros-dev/src/yolov5s.plan input_binding_names:=['images'] output_binding_names:=['output0'] network_image_width:=640 network_image_height:=640
``` 

The following error occurs.

```
[component_container_mt-1] 2023-06-14 12:31:34.621 ERROR gxf/std/program.cpp@475: Attempted interrupting when not running (state=0d).
[component_container_mt-1] 2023-06-14 12:31:34.621 ERROR gxf/core/runtime.cpp@1243: Graph interrupt failed with error: GXF_INVALID_EXECUTION_SEQUENCE
```

Full log from console

```
[INFO] [launch]: All log files can be found below /home/nvidia/.ros/log/2023-06-14-12-28-05-019641-tul01-45998
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'rqt_image_view' not found, searching: ['/home/nvidia/ws/install/yolov5_isaac_ros', '/home/nvidia/ws/install/isaac_ros_triton', '/home/nvidia/ws/install/isaac_ros_test', '/home/nvidia/ws/install/isaac_ros_tensor_rt', '/home/nvidia/ws/install/isaac_ros_dnn_encoders', '/home/nvidia/ws/install/isaac_ros_nitros_tensor_list_type', '/home/nvidia/ws/install/isaac_ros_dnn_inference_test', '/home/nvidia/ws/install/isaac_ros_tensor_list_interfaces', '/home/nvidia/ws/install/isaac_ros_image_pipeline', '/home/nvidia/ws/install/isaac_ros_stereo_image_proc', '/home/nvidia/ws/install/isaac_ros_nitros_flat_scan_type', '/home/nvidia/ws/install/isaac_ros_pointcloud_interfaces', '/home/nvidia/ws/install/isaac_ros_nitros_std_msg_type', '/home/nvidia/ws/install/isaac_ros_nitros_pose_cov_stamped_type', '/home/nvidia/ws/install/isaac_ros_nitros_pose_array_type', '/home/nvidia/ws/install/isaac_ros_nitros_point_cloud_type', '/home/nvidia/ws/install/isaac_ros_nitros_occupancy_grid_type', '/home/nvidia/ws/install/isaac_ros_nitros_imu_type', '/home/nvidia/ws/install/isaac_ros_image_proc', '/home/nvidia/ws/install/isaac_ros_nitros_image_type', '/home/nvidia/ws/install/isaac_ros_nitros_disparity_image_type', '/home/nvidia/ws/install/isaac_ros_nitros_detection2_d_array_type', '/home/nvidia/ws/install/isaac_ros_nitros_compressed_image_type', '/home/nvidia/ws/install/isaac_ros_nitros_camera_info_type', '/home/nvidia/ws/install/isaac_ros_nitros_april_tag_detection_array_type', '/home/nvidia/ws/install/isaac_ros_nitros', '/home/nvidia/ws/install/isaac_ros_nitros_interfaces', '/home/nvidia/ws/install/isaac_ros_gxf', '/home/nvidia/ws/install/isaac_ros_common', '/home/nvidia/ws/install/isaac_ros_bi3d_interfaces', '/home/nvidia/ws/install/isaac_ros_apriltag_interfaces', '/home/nvidia/ros/humble/install']"
[INFO] [component_container_mt-1]: process started with pid [46012]
[INFO] [Yolov5Decoder-2]: process started with pid [46014]
[INFO] [isaac_ros_yolov5_visualizer-3]: process started with pid [46016]
[component_container_mt-1] 2023-06-14 12:28:06.136 WARN  gxf/std/program.cpp@456: No system specified. Nothing to do
[component_container_mt-1] [INFO] [1686716885.972180422] [yolov5_container]: Load Library: /home/nvidia/ws/install/isaac_ros_dnn_encoders/lib/libdnn_image_encoder_node.so
[component_container_mt-1] [INFO] [1686716886.092177568] [yolov5_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode>
[component_container_mt-1] [INFO] [1686716886.092339432] [yolov5_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode>
[component_container_mt-1] [INFO] [1686716886.102909764] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container_mt-1] [INFO] [1686716886.103411582] [dnn_image_encoder]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1686716886.105051538] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container_mt-1] [INFO] [1686716886.111898032] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container_mt-1] [INFO] [1686716886.116526685] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container_mt-1] [INFO] [1686716886.121592416] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container_mt-1] [INFO] [1686716886.127907331] [NitrosContext]: [NitrosContext] Loading application: '/home/nvidia/ws/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container_mt-1] [INFO] [1686716886.130458982] [NitrosContext]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1686716886.136789129] [NitrosContext]: [NitrosContext] Running application...
[component_container_mt-1] [INFO] [1686716886.138982906] [dnn_image_encoder]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1686716886.139072190] [dnn_image_encoder]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1686716886.146371188] [dnn_image_encoder]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1686716886.146482873] [dnn_image_encoder]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1686716886.151919855] [dnn_image_encoder]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1686716886.152032181] [dnn_image_encoder]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1686716886.152938371] [dnn_image_encoder]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1686716886.153771790] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container_mt-1] [INFO] [1686716886.156576798] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container_mt-1] [INFO] [1686716886.160628397] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container_mt-1] [INFO] [1686716886.165796245] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/image_proc/libgxf_tensorops.so
[component_container_mt-1] [INFO] [1686716886.174824355] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/multimedia/libgxf_multimedia.so
[component_container_mt-1] [INFO] [1686716886.176357681] [dnn_image_encoder]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1686716886.196636511] [dnn_image_encoder]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1686716886.556033165] [dnn_image_encoder]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1686716886.563780698] [dnn_image_encoder]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1686716886.593299488] [dnn_image_encoder]: [NitrosNode] Starting negotiation...
[INFO] [component_container_mt-1]: sending signal 'SIGINT' to process[component_container_mt-1]
[INFO] [Yolov5Decoder-2]: sending signal 'SIGINT' to process[Yolov5Decoder-2]
[INFO] [isaac_ros_yolov5_visualizer-3]: sending signal 'SIGINT' to process[isaac_ros_yolov5_visualizer-3]
[component_container_mt-1] [INFO] [1686716886.621783345] [rclcpp]: signal_handler(signum=2)
[component_container_mt-1] [INFO] [1686716886.626326873] [dnn_image_encoder]: [NitrosNode] Terminating the running application
[component_container_mt-1] [INFO] [1686716886.626382492] [dnn_image_encoder]: [NitrosContext] Interrupting GXF...
[component_container_mt-1] 2023-06-14 12:28:06.626 ERROR gxf/std/program.cpp@475: Attempted interrupting when not running (state=0d).
[component_container_mt-1] 2023-06-14 12:28:06.626 ERROR gxf/core/runtime.cpp@1243: Graph interrupt failed with error: GXF_INVALID_EXECUTION_SEQUENCE
[component_container_mt-1] [ERROR] [1686716886.626471776] [dnn_image_encoder]: [NitrosContext] GxfGraphInterrupt Error: GXF_INVALID_EXECUTION_SEQUENCE
[component_container_mt-1] [INFO] [1686716886.626488353] [dnn_image_encoder]: [NitrosContext] Waiting on GXF...
[component_container_mt-1] [INFO] [1686716886.626513282] [dnn_image_encoder]: [NitrosContext] Deinitializing...
[component_container_mt-1] [INFO] [1686716886.626539876] [dnn_image_encoder]: [NitrosContext] Destroying context
[isaac_ros_yolov5_visualizer-3] Traceback (most recent call last):
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/yolov5_isaac_ros/isaac_ros_yolov5_visualizer", line 33, in <module>
[isaac_ros_yolov5_visualizer-3]     sys.exit(load_entry_point('yolov5-isaac-ros==0.0.0', 'console_scripts', 'isaac_ros_yolov5_visualizer')())
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/python3.8/site-packages/yolov5_isaac_ros/isaac_ros_yolov5_visualizer.py", line 95, in main
[isaac_ros_yolov5_visualizer-3]     rclpy.spin(Yolov5Visualizer())
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/__init__.py", line 222, in spin
[isaac_ros_yolov5_visualizer-3]     executor.spin_once()
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 705, in spin_once
[isaac_ros_yolov5_visualizer-3]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 691, in wait_for_ready_callbacks
[isaac_ros_yolov5_visualizer-3]     return next(self._cb_iter)
[isaac_ros_yolov5_visualizer-3]   File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/executors.py", line 588, in _wait_for_ready_callbacks
[isaac_ros_yolov5_visualizer-3]     wait_set.wait(timeout_nsec)
[isaac_ros_yolov5_visualizer-3] KeyboardInterrupt
[component_container_mt-1] [INFO] [1686716886.627803396] [dnn_image_encoder]: [NitrosNode] Application termination done
[ERROR] [isaac_ros_yolov5_visualizer-3]: process has died [pid 46016, exit code -2, cmd '/home/nvidia/ws/install/yolov5_isaac_ros/lib/yolov5_isaac_ros/isaac_ros_yolov5_visualizer --ros-args -r __node:=yolov5_visualizer_node'].
[INFO] [component_container_mt-1]: process has finished cleanly [pid 46012]
[WARNING] [launch_ros.actions.load_composable_nodes]: Abandoning wait for the '/yolov5_container/_container/load_node' service response, due to shutdown.
Future exception was never retrieved
future: <Future finished exception=InvalidHandle('cannot use Destroyable because destruction was requested')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/launch_ros/actions/load_composable_nodes.py", line 197, in _load_in_sequence
    self._load_node(next_load_node_request, context)
  File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/launch_ros/actions/load_composable_nodes.py", line 119, in _load_node
    while not self.__rclpy_load_node_client.wait_for_service(timeout_sec=1.0):
  File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/client.py", line 180, in wait_for_service
    return self.service_is_ready()
  File "/home/nvidia/ros/humble/install/lib/python3.8/site-packages/rclpy/client.py", line 159, in service_is_ready
    with self.handle:
rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested
[Yolov5Decoder-2] Traceback (most recent call last):
[Yolov5Decoder-2]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/yolov5_isaac_ros/Yolov5Decoder", line 33, in <module>
[Yolov5Decoder-2]     sys.exit(load_entry_point('yolov5-isaac-ros==0.0.0', 'console_scripts', 'Yolov5Decoder')())
[Yolov5Decoder-2]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/yolov5_isaac_ros/Yolov5Decoder", line 25, in importlib_load_entry_point
[Yolov5Decoder-2]     return next(matches).load()
[Yolov5Decoder-2]   File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
[Yolov5Decoder-2]     module = import_module(match.group('module'))
[Yolov5Decoder-2]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[Yolov5Decoder-2]     return _bootstrap._gcd_import(name[level:], package, level)
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
[Yolov5Decoder-2]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Yolov5Decoder-2]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/python3.8/site-packages/yolov5_isaac_ros/Yolov5Decoder.py", line 17, in <module>
[Yolov5Decoder-2]     from yolov5_isaac_ros.Yolov5DecoderUtils import tensor_to_torch_array
[Yolov5Decoder-2]   File "/home/nvidia/ws/install/yolov5_isaac_ros/lib/python3.8/site-packages/yolov5_isaac_ros/Yolov5DecoderUtils.py", line 20, in <module>
[Yolov5Decoder-2]     import torch
[Yolov5Decoder-2]   File "/home/nvidia/.local/lib/python3.8/site-packages/torch/__init__.py", line 229, in <module>
[Yolov5Decoder-2]     from torch._C import *  # noqa: F403
[Yolov5Decoder-2] KeyboardInterrupt
[ERROR] [Yolov5Decoder-2]: process has died [pid 46014, exit code -2, cmd '/home/nvidia/ws/install/yolov5_isaac_ros/lib/yolov5_isaac_ros/Yolov5Decoder --ros-args -r __node:=yolov5_decoder_node --params-file /home/nvidia/ws/install/yolov5_isaac_ros/share/yolov5_isaac_ros/config/decoder_params.yaml'].
```

I'm running Isaac ROS on jetson AGX with the following packages.
```
jtop 4.2.1 - (c) 2023, Raffaello Bonghi [raffaello@rnext.it]
Website: https://rnext.it/jetson_stats

 Platform                          Serial Number: [s|XX CLICK TO READ XXX]
  Machine: aarch64                 Hardware
  System: Linux                     Model: Jetson-AGX
  Distribution: Ubuntu 20.04 focal  699-level Part Number: 699-82888-0004-400 R.0
  Release: 5.10.104-tegra           P-Number: p2888-0004
  Python: 3.8.10                    Module: NVIDIA Jetson AGX Xavier (32 GB ram)
                                    SoC: tegra194
 Libraries                          CUDA Arch BIN: 7.2
  CUDA: 11.4.315                    Codename: Galen
  cuDNN: 8.6.0.166                  L4T: 35.3.1
  TensorRT: 8.5.2.2                 Jetpack: 5.1.1
  VPI: 2.2.7
  Vulkan: 1.3.204                  Hostname: tul01
  OpenCV: 4.5.4 with CUDA: NO
```

**Comment by khaledgabr77** [comment]
The error message you provided indicates that the package `rqt_image_view` is not found, suggesting that you haven't installed it. To resolve this issue, you should install the package using the following command:
`sudo apt install ros-humble-rqt-image-view
`
